export const patients = [
  { id: 'p1', name: 'Sarah Khan', email: 'sarah.khan@email.com', phone: '+92-301-2345678', dob: '1995-03-15', gender: 'Female', avatar: null, bloodGroup: 'A+', address: 'House 42, Street 7, Islamabad' },
  { id: 'p2', name: 'Ali Raza', email: 'ali.raza@email.com', phone: '+92-302-3456789', dob: '1988-07-22', gender: 'Male', avatar: null, bloodGroup: 'B+', address: 'Flat 12, Block C, Lahore' },
  { id: 'p3', name: 'Ahmed Hassan', email: 'ahmed.h@email.com', phone: '+92-303-4567890', dob: '1992-11-08', gender: 'Male', avatar: null, bloodGroup: 'O+', address: 'Sector G-9, Islamabad' },
  { id: 'p4', name: 'Maria Fatima', email: 'maria.f@email.com', phone: '+92-304-5678901', dob: '1990-01-30', gender: 'Female', avatar: null, bloodGroup: 'AB+', address: 'DHA Phase 5, Karachi' },
  { id: 'p5', name: 'Usman Tariq', email: 'usman.t@email.com', phone: '+92-305-6789012', dob: '1985-09-12', gender: 'Male', avatar: null, bloodGroup: 'A-', address: 'Model Town, Lahore' },
];
export const doctors = [
  { id: 'd1', name: 'Dr. Ahmed Khan', specialty: 'Cardiologist', email: 'ahmed.khan@hospital.com', phone: '+92-310-1234567', available: true, rating: 4.8, patients: 24, avatar: null, room: 'Room 201', experience: '15 years' },
  { id: 'd2', name: 'Dr. Ayesha Siddiqui', specialty: 'Neurologist', email: 'ayesha.s@hospital.com', phone: '+92-310-2345678', available: true, rating: 4.9, patients: 18, avatar: null, room: 'Room 305', experience: '12 years' },
  { id: 'd3', name: 'Dr. Bilal Ahmad', specialty: 'Orthopedic', email: 'bilal.a@hospital.com', phone: '+92-310-3456789', available: false, rating: 4.7, patients: 30, avatar: null, room: 'Room 108', experience: '20 years' },
  { id: 'd4', name: 'Dr. Sara Malik', specialty: 'Dermatologist', email: 'sara.m@hospital.com', phone: '+92-310-4567890', available: true, rating: 4.6, patients: 15, avatar: null, room: 'Room 402', experience: '8 years' },
  { id: 'd5', name: 'Dr. Omar Farooq', specialty: 'General Physician', email: 'omar.f@hospital.com', phone: '+92-310-5678901', available: true, rating: 4.5, patients: 42, avatar: null, room: 'Room 101', experience: '10 years' },
];
export const appointments = [
  { id: 'a1', patientId: 'p1', doctorId: 'd1', patientName: 'Sarah Khan', doctorName: 'Dr. Ahmed Khan', specialty: 'Cardiologist', date: '2026-09-04', time: '10:30 AM', location: 'Room 201, Block A', status: 'upcoming', type: 'Follow-up' },
  { id: 'a2', patientId: 'p1', doctorId: 'd5', patientName: 'Sarah Khan', doctorName: 'Dr. Omar Farooq', specialty: 'General Physician', date: '2026-09-10', time: '2:00 PM', location: 'Room 101, Block B', status: 'upcoming', type: 'Consultation' },
  { id: 'a3', patientId: 'p2', doctorId: 'd2', patientName: 'Ali Raza', doctorName: 'Dr. Ayesha Siddiqui', specialty: 'Neurologist', date: '2026-09-03', time: '11:00 AM', location: 'Room 305, Block C', status: 'upcoming', type: 'Check-up' },
  { id: 'a4', patientId: 'p1', doctorId: 'd4', patientName: 'Sarah Khan', doctorName: 'Dr. Sara Malik', specialty: 'Dermatologist', date: '2026-08-20', time: '9:00 AM', location: 'Room 402, Block A', status: 'completed', type: 'Consultation' },
  { id: 'a5', patientId: 'p1', doctorId: 'd1', patientName: 'Sarah Khan', doctorName: 'Dr. Ahmed Khan', specialty: 'Cardiologist', date: '2026-08-15', time: '10:00 AM', location: 'Room 201, Block A', status: 'completed', type: 'Check-up' },
  { id: 'a6', patientId: 'p3', doctorId: 'd3', patientName: 'Ahmed Hassan', doctorName: 'Dr. Bilal Ahmad', specialty: 'Orthopedic', date: '2026-09-05', time: '3:00 PM', location: 'Room 108, Block B', status: 'upcoming', type: 'Follow-up' },
  { id: 'a7', patientId: 'p4', doctorId: 'd1', patientName: 'Maria Fatima', doctorName: 'Dr. Ahmed Khan', specialty: 'Cardiologist', date: '2026-09-04', time: '11:30 AM', location: 'Room 201, Block A', status: 'upcoming', type: 'Consultation' },
  { id: 'a8', patientId: 'p5', doctorId: 'd5', patientName: 'Usman Tariq', doctorName: 'Dr. Omar Farooq', specialty: 'General Physician', date: '2026-08-25', time: '1:00 PM', location: 'Room 101, Block B', status: 'cancelled', type: 'Consultation' },
  { id: 'a9', patientId: 'p2', doctorId: 'd1', patientName: 'Ali Raza', doctorName: 'Dr. Ahmed Khan', specialty: 'Cardiologist', date: '2026-09-01', time: '9:30 AM', location: 'Room 201, Block A', status: 'completed', type: 'Follow-up' },
  { id: 'a10', patientId: 'p3', doctorId: 'd2', patientName: 'Ahmed Hassan', doctorName: 'Dr. Ayesha Siddiqui', specialty: 'Neurologist', date: '2026-09-06', time: '10:00 AM', location: 'Room 305, Block C', status: 'upcoming', type: 'Consultation' },
];
export const reports = [
  { id: 'r1', patientId: 'p1', name: 'Complete Blood Count (CBC)', type: 'Blood', date: '2026-08-28', doctorName: 'Dr. Ahmed Khan', status: 'ready', hospital: 'MediSync Central Hospital', findings: 'All parameters within normal range. WBC: 7,200/uL, RBC: 4.8M/uL, Hemoglobin: 14.2 g/dL, Platelets: 250,000/uL', aiSummary: 'Your CBC results are within normal ranges. White blood cell count is healthy, indicating no active infection. Red blood cell count and hemoglobin levels are optimal. Platelet count is normal.' },
  { id: 'r2', patientId: 'p1', name: 'Electrocardiogram (ECG)', type: 'ECG', date: '2026-08-25', doctorName: 'Dr. Ahmed Khan', status: 'ready', hospital: 'MediSync Central Hospital', findings: 'Normal sinus rhythm. Heart rate: 72 bpm. PR interval: 160ms. QRS duration: 88ms.', aiSummary: 'Your ECG shows a normal heart rhythm with a rate of 72 beats per minute. All intervals and segments are within normal limits.' },
  { id: 'r3', patientId: 'p1', name: 'Lipid Panel', type: 'Blood', date: '2026-08-20', doctorName: 'Dr. Omar Farooq', status: 'ready', hospital: 'MediSync Central Hospital', findings: 'Total Cholesterol: 195 mg/dL, LDL: 110 mg/dL, HDL: 55 mg/dL, Triglycerides: 150 mg/dL', aiSummary: 'Your lipid panel shows borderline cholesterol levels. LDL is slightly elevated. Consider dietary modifications and regular exercise.' },
  { id: 'r4', patientId: 'p1', name: 'Chest X-Ray', type: 'Imaging', date: '2026-08-15', doctorName: 'Dr. Ahmed Khan', status: 'ready', hospital: 'MediSync Central Hospital', findings: 'Clear lung fields bilaterally. No consolidation, effusion, or pneumothorax.', aiSummary: 'Your chest X-ray is completely normal. Lungs are clear with no abnormalities detected.' },
  { id: 'r5', patientId: 'p2', name: 'MRI Brain', type: 'Imaging', date: '2026-08-22', doctorName: 'Dr. Ayesha Siddiqui', status: 'ready', hospital: 'MediSync Central Hospital', findings: 'No acute intracranial abnormality.', aiSummary: 'Brain MRI is normal with no structural abnormalities detected.' },
  { id: 'r6', patientId: 'p3', name: 'X-Ray Left Knee', type: 'Imaging', date: '2026-08-18', doctorName: 'Dr. Bilal Ahmad', status: 'ready', hospital: 'MediSync Central Hospital', findings: 'Mild joint space narrowing medially. Small osteophyte formation.', aiSummary: 'X-ray shows mild wear-and-tear changes in the left knee joint. Recommend physiotherapy.' },
  { id: 'r7', patientId: 'p1', name: 'Thyroid Function Test', type: 'Blood', date: '2026-08-10', doctorName: 'Dr. Omar Farooq', status: 'ready', hospital: 'MediSync Central Hospital', findings: 'TSH: 2.5 mIU/L, Free T4: 1.2 ng/dL, Free T3: 3.1 pg/mL', aiSummary: 'Thyroid function is completely normal. All hormone levels are within the healthy range.' },
  { id: 'r8', patientId: 'p4', name: 'Echocardiogram', type: 'ECG', date: '2026-08-27', doctorName: 'Dr. Ahmed Khan', status: 'pending', hospital: 'MediSync Central Hospital', findings: 'Pending review', aiSummary: 'Report is currently pending review by the cardiologist.' },
];
export const prescriptions = [
  { id: 'pr1', patientId: 'p1', medicine: 'Atorvastatin', dosage: '10mg', frequency: 'Once daily', duration: '30 days', doctorName: 'Dr. Ahmed Khan', date: '2026-08-28', status: 'active', instructions: 'Take after dinner' },
  { id: 'pr2', patientId: 'p1', medicine: 'Aspirin', dosage: '75mg', frequency: 'Once daily', duration: '90 days', doctorName: 'Dr. Ahmed Khan', date: '2026-08-25', status: 'active', instructions: 'Take after breakfast' },
  { id: 'pr3', patientId: 'p1', medicine: 'Vitamin D3', dosage: '2000 IU', frequency: 'Once daily', duration: '60 days', doctorName: 'Dr. Omar Farooq', date: '2026-08-20', status: 'active', instructions: 'Take with milk' },
  { id: 'pr4', patientId: 'p2', medicine: 'Gabapentin', dosage: '300mg', frequency: 'Twice daily', duration: '14 days', doctorName: 'Dr. Ayesha Siddiqui', date: '2026-08-22', status: 'active', instructions: 'Take after meals' },
  { id: 'pr5', patientId: 'p1', medicine: 'Amoxicillin', dosage: '500mg', frequency: 'Three times daily', duration: '7 days', doctorName: 'Dr. Omar Farooq', date: '2026-07-15', status: 'completed', instructions: 'Take after meals. Complete full course.' },
];
export const notifications = [
  { id: 'n1', type: 'appointment', title: 'Appointment Reminder', message: 'Your appointment with Dr. Ahmed Khan is tomorrow at 10:30 AM.', time: '2026-09-01T08:00:00', read: false },
  { id: 'n2', type: 'report', title: 'Report Available', message: 'Your CBC report from August 28 is now available to view.', time: '2026-08-28T14:30:00', read: false },
  { id: 'n3', type: 'queue', title: 'Queue Update', message: 'Your queue position is now #04. Estimated wait: 18 minutes.', time: '2026-09-01T09:15:00', read: false },
  { id: 'n4', type: 'doctor', title: 'Message from Dr. Ahmed', message: 'Dr. Ahmed Khan has reviewed your ECG report. Everything looks good.', time: '2026-08-26T11:00:00', read: true },
  { id: 'n5', type: 'system', title: 'Profile Updated', message: 'Your profile information has been successfully updated.', time: '2026-08-25T16:45:00', read: true },
  { id: 'n6', type: 'appointment', title: 'Appointment Confirmed', message: 'Your appointment with Dr. Omar Farooq on Sep 10 has been confirmed.', time: '2026-08-24T10:00:00', read: true },
  { id: 'n7', type: 'report', title: 'Report Ready', message: 'Your Lipid Panel report is now available.', time: '2026-08-20T13:20:00', read: true },
  { id: 'n8', type: 'system', title: 'Maintenance Notice', message: 'System maintenance scheduled for September 15, 2:00 AM - 4:00 AM.', time: '2026-08-19T09:00:00', read: false },
  { id: 'n9', type: 'doctor', title: 'Prescription Renewed', message: 'Dr. Ahmed Khan has renewed your Atorvastatin prescription.', time: '2026-08-28T15:00:00', read: false },
  { id: 'n10', type: 'queue', title: 'Queue Joined', message: 'You have been added to Dr. Ahmed Khan\'s queue. Position: #07.', time: '2026-08-15T08:30:00', read: true },
];
export const queueData = { currentServing: 1, yourPosition: 4, estimatedWait: 18, doctor: 'Dr. Ahmed Khan', room: 'Room 201', appointmentTime: '10:30 AM', queue: [{ position: 1, name: 'Hassan Ali', status: 'serving' }, { position: 2, name: 'Fatima Noor', status: 'waiting' }, { position: 3, name: 'Zain Ahmed', status: 'waiting' }, { position: 4, name: 'Sarah Khan (You)', status: 'you' }, { position: 5, name: 'Ayesha Bibi', status: 'waiting' }, { position: 6, name: 'Bilal Khan', status: 'waiting' }] };
export const chatHistory = [{ id: 'c1', role: 'assistant', content: 'Hi Sarah! I\'m your MediSync healthcare assistant. How can I help you today?', timestamp: '2026-09-01T09:00:00' }];
export const chatConversations = [{ id: 'conv1', title: 'Latest Report Inquiry', date: '2026-09-01', messages: [] }, { id: 'conv2', title: 'Appointment Booking', date: '2026-08-28', messages: [] }, { id: 'conv3', title: 'Prescription Questions', date: '2026-08-25', messages: [] }];
export const mockResponses = { report: 'I found your latest CBC report from August 28, 2026. All parameters within normal range. Would you like me to summarize it?', appointment: 'Your next appointment is with Dr. Ahmed Khan on September 4 at 10:30 AM in Room 201, Block A.', queue: 'You are currently #04 in Dr. Ahmed Khan\'s queue. Estimated waiting time is approximately 18 minutes.', prescription: 'You have 3 active prescriptions: Atorvastatin 10mg, Aspirin 75mg, and Vitamin D3 2000 IU.', summarize: 'Based on your latest reports: CBC is normal, ECG shows healthy rhythm, lipid panel shows borderline cholesterol. Overall health is good.', default: 'I can help you with medical reports, appointments, prescriptions, queue status, and general health information.' };
export const activityTimeline = [{ id: 'at1', type: 'report', title: 'CBC Report Available', description: 'Your Complete Blood Count report has been uploaded.', time: '2 hours ago', icon: 'FileText' }, { id: 'at2', type: 'appointment', title: 'Appointment Confirmed', description: 'Dr. Ahmed Khan confirmed your Sep 4 appointment.', time: '5 hours ago', icon: 'Calendar' }, { id: 'at3', type: 'prescription', title: 'Prescription Renewed', description: 'Atorvastatin 10mg renewed for 30 days.', time: '1 day ago', icon: 'Pill' }, { id: 'at4', type: 'message', title: 'Doctor Message', description: 'Dr. Ahmed reviewed your ECG - all clear.', time: '2 days ago', icon: 'MessageCircle' }];
export const specialties = ['Cardiologist', 'Neurologist', 'Orthopedic', 'Dermatologist', 'General Physician', 'Pediatrician', 'Ophthalmologist', 'ENT Specialist', 'Psychiatrist', 'Dentist'];
export const timeSlots = ['9:00 AM', '9:30 AM', '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM', '2:00 PM', '2:30 PM', '3:00 PM', '3:30 PM', '4:00 PM', '4:30 PM'];
export const doctorSchedule = [{ time: '9:00 AM', patient: 'Sarah Khan', type: 'Follow-up', status: 'completed' }, { time: '9:30 AM', patient: 'Ali Raza', type: 'Check-up', status: 'completed' }, { time: '10:00 AM', patient: 'Hassan Ali', type: 'Consultation', status: 'in-progress' }, { time: '10:30 AM', patient: 'Sarah Khan', type: 'Follow-up', status: 'upcoming' }, { time: '11:00 AM', patient: 'Fatima Noor', type: 'Consultation', status: 'upcoming' }, { time: '11:30 AM', patient: 'Maria Fatima', type: 'Consultation', status: 'upcoming' }];
export const adminStats = { totalPatients: 1247, totalDoctors: 48, todayAppointments: 156, activeQueues: 12, monthlyRevenue: 'PKR 4.2M', satisfaction: 94 };
export const appointmentsOverTime = [{ month: 'Mar', appointments: 320 }, { month: 'Apr', appointments: 380 }, { month: 'May', appointments: 410 }, { month: 'Jun', appointments: 390 }, { month: 'Jul', appointments: 450 }, { month: 'Aug', appointments: 480 }, { month: 'Sep', appointments: 156 }];
export const patientRegistrations = [{ month: 'Mar', registrations: 85 }, { month: 'Apr', registrations: 92 }, { month: 'May', registrations: 110 }, { month: 'Jun', registrations: 98 }, { month: 'Jul', registrations: 125 }, { month: 'Aug', registrations: 140 }, { month: 'Sep', registrations: 45 }];
export const queueActivityData = [{ hour: '8AM', active: 3 }, { hour: '9AM', active: 8 }, { hour: '10AM', active: 12 }, { hour: '11AM', active: 15 }, { hour: '12PM', active: 10 }, { hour: '1PM', active: 6 }, { hour: '2PM', active: 11 }, { hour: '3PM', active: 14 }, { hour: '4PM', active: 9 }, { hour: '5PM', active: 4 }];
